import type { AdminUser } from "@/types/admin";

// Mock data — replace with real API data when backend is ready
export const MOCK_USERS: AdminUser[] = [
  {
    id: "1",
    name: "David Okonkwo",
    email: "david@exampke.com",
    tier: "beginner",
    projects: 3,
    lastActive: "2 min ago",
    revenue: "$19/mo",
    status: "active",
  },
  {
    id: "2",
    name: "Elizabeth Kimani",
    email: "elizabeth@sample.com",
    tier: "pro",
    projects: 7,
    lastActive: "8 min ago",
    revenue: "$49/mo",
    status: "active",
  },
  {
    id: "3",
    name: "Maya Adesanya",
    email: "maya@sample.com",
    tier: "free",
    projects: 2,
    lastActive: "14 min ago",
    revenue: "$0(referral: $2.40)",
    status: "active",
  },
  {
    id: "4",
    name: "Chidi Nnamdi",
    email: "chidi@sample.com",
    tier: "beginner",
    projects: 1,
    lastActive: "22 min ago",
    revenue: "$19/mo",
    status: "active",
  },
  {
    id: "5",
    name: "Ben Johnson",
    email: "ben@sample.com",
    tier: "beginner",
    projects: 4,
    lastActive: "3 days ago",
    revenue: "$19/mo",
    status: "idle",
  },
  {
    id: "6",
    name: "Sarah Kofi",
    email: "sarah@sample.com",
    tier: "free",
    projects: 1,
    lastActive: "12 days ago",
    revenue: "$0",
    status: "churned",
  },
];
